project:
  type: website
  output-dir: docs

website:
  title: "Muizz Aman Khan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: sql_project.qmd
            text: SQL
          - href: text_analysis_project.qmd
            text: Text Analysis
          - href: allin1_project.qmd
            text: R Package (allin1)
          - href: poster_project.qmd
            text: Poster (S → R)
          - href: rhombus_project.qmd
            text: Rhombus StreamDeck Plugin
      - href: other_side.qmd
        text: My Other Side

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



